### ISSUE TITLE
How to use TypedRoute

### ISSUE THREAD

**Issue by sacru2red** [samchon/nestia#215]
## Question
I'm trying to use nestia
I have a warning under
```
C:\Users\userName\Desktop\nestjs-cli-created\node_modules\@nestia\core\src\decorators\TypedRoute.ts:97
            )(...args);
             ^
Error: Error on nestia.core.TypedRoute.Get(): no stringify function provided.
    at C:\Users\userName\Desktop\nestjs-cli-created\node_modules\@nestia\core\src\decorators\internal\get_path_and_stringify.ts:26:19
    at C:\Users\userName\Desktop\nestjs-cli-created\node_modules\@nestia\core\src\decorators\internal\get_path_and_stringify.ts:19:48
    at Object.route [as Get] (C:\Users\userName\Desktop\nestjs-cli-created\node_modules\@nestia\core\src\decorators\TypedRoute.ts:97:14)
    at Object.<anonymous> (C:\Users\userName\Desktop\nestjs-cli-created\src\app.controller.ts:21:20)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
```

refer
[nestjs-cli-created-nestia](https://github.com/sacru2red/nestjs-cli-created-nestia)

**Comment by 39hn** [comment]
you should use `ttypescript`'s `ttsc` compiler to apply nestia's custom transformer.

hence, try something like below
`package.json`
```json
{
  "scripts": {
    "prebuild": "rimraf dist",
    "build": "ttsc -p tsconfig.build.json",
    "start": "node dist/main"
  }
}
```

`command`
```
npm run build
npm run start
```
