### ISSUE TITLE
`encrypted` test always fail on SDK

### ISSUE THREAD

**Issue by 39hn** [samchon/nestia#231]
### Summary
Write a short summary of the bug in here.

  - **SDK Version**: 1.0.4
  - **Expected behavior**: All tests should pass
  - **Actual behavior**: `encrypted` tests are failling

```bash
> @nestia/sdk@1.0.4 test
> node lib/test

Build Demonstration Projects
---------------------------------------------------------
176 -> npx nestia swagger src/controllers --out ./
encrypted -> npx nestia swagger src/controllers --out ./
generic -> npx nestia swagger src/controllers --out ./
recursive -> npx nestia swagger src/**/*.controller.ts --out ./
safe -> npx nestia swagger src/controllers --out ./
union -> npx nestia swagger src/controllers --out ./
multiple-paths -> npx nestia swagger src/controllers --out ./
---------------------------------------------------------
176 -> npx nestia sdk src/controllers --out src/api
encrypted -> npx nestia sdk src/controllers --out src/api
generic -> npx nestia sdk src/controllers --out src/api
recursive -> npx nestia sdk src/**/*.controller.ts --out src/api
safe -> npx nestia sdk src/controllers --out src/api
union -> npx nestia sdk src/controllers --out src/api
multiple-paths -> npx nestia sdk src/controllers --out src/api
---------------------------------------------------------
176 -> npx ts-node -C ttypescript src/test
  - test_userspace_type1: 43 ms
  - test_userspace_type2: 6 ms
encrypted -> npx ts-node -C ttypescript src/test
  - test_seller_exit -> TypeError
TypeError: Cannot convert argument to a ByteString because the character at index 35 has a value of 45824 which is greater than 255.
    at Object.fetch (node:internal/deps/undici/undici:14062:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
Error: Command failed: npx ts-node -C ttypescript src/test
    at checkExecSyncError (node:child_process:885:11)
    at Object.execSync (node:child_process:957:15)
    at Object.<anonymous> (/Users/USERNAME/Works/nestia/packages/sdk/lib/test/TestBuilder.js:51:41)
    at Generator.next (<anonymous>)
    at /Users/USERNAME/Works/nestia/packages/sdk/lib/test/TestBuilder.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/USERNAME/Works/nestia/packages/sdk/lib/test/TestBuilder.js:4:12)
    at Object.test (/Users/USERNAME/Works/nestia/packages/sdk/lib/test/TestBuilder.js:48:16)
    at WorkerServer.<anonymous> (/Users/USERNAME/Works/nestia/packages/sdk/node_modules/tgrid/components/Communicator.js:397:51) {
  status: 255,
  signal: null,
  output: [ null, null, null ],
  pid: 64635,
  stdout: null,
  stderr: null
}
```

### Code occuring the bug

1. Go to `nestia/packages/sdk` directory.
2. Run `npm run build` script.
3. Run `npm run test` script.

**Comment by samchon** [comment]
No problem on both Windows and Linux Ubuntu environments.

Can you tell me your environments including NodeJS version?

**Comment by 39hn** [comment]
MacBook Pro 15-inch, 2018 (intel core i7)
macos ventura 13.1(22C65)

node : v18.13.0

**Comment by 39hn** [comment]
all tests passed when i excluded encrypted one.
and if i excluded other tests but encrypted, the test failed.

**Comment by samchon** [comment]
How? you mean modified some test automation program's code? Can you show me how updated?

**Comment by 39hn** [comment]
sdk/src/test/index.ts
```ts
async function main(): Promise<void> {
    console.log("Build Demonstration Projects");
    for (const job of ["swagger", "sdk", "test"] as const) {
        console.log(
            "---------------------------------------------------------",
        );
        // await execute("176", job, get_arguments("directory", job));
        await execute("encrypted", job, get_arguments("directory", job));
        // await execute("generic", job, get_arguments("directory", job));
        // await execute("recursive", job, get_arguments("pattern", job));
        // await execute("safe", job, get_arguments("directory", job));
        // await execute("union", job, get_arguments("directory", job));
        // await execute("multiple-paths", job, get_arguments("directory", job));
    }
}
```

yup I edited test file like this

**Comment by samchon** [comment]
I will test it after home.

**Comment by samchon** [comment]
No problem even in macbook environments:

  - only encrypted: https://github.com/samchon/nestia/actions/runs/4022257303/jobs/6911833045#step:6:35
  - everything: https://github.com/samchon/nestia/actions/runs/4022271694/jobs/6911861434#step:6:68

**Comment by 39hn** [comment]
```bash
> @nestia/sdk@1.0.4 test
> node lib/test

Build Demonstration Projects
---------------------------------------------------------
encrypted -> npx nestia swagger src/controllers --out ./
---------------------------------------------------------
encrypted -> npx nestia sdk src/controllers --out src/api
---------------------------------------------------------
encrypted -> npx ts-node -C ttypescript src/test
  - test_seller_exit: 71 ms
  - test_seller_join: 5 ms
  - test_seller_login: 5 ms
  - test_seller_password_change: 7 ms
```
I also pass the test after update os to ventura 13.2(22D49).
smh
