### ISSUE TITLE
Error on swagger with Typescript 5.5.2 installed by typia setup

### ISSUE THREAD

**Issue by Devidian** [samchon/nestia#969]
Our latest deployment pipeline failed due to the fact that `typia setup` ( `yarn typia setup --manager yarn --project tsconfig.json`) installed `typescript@5.5.2`. The execution of `yarn nestia swagger _app_`  ends with:

```
Analyzing reflections
  - controllers: #16
  - paths: #59
  - routes: #59
Analyzing source codes
Error: target is a string value; tsconfig JSON must be parsed with parseJsonSourceFileConfigFileContent or getParsedCommandLineOfConfigFile before passing to createProgram
    at Proxy.originalCreateProgram (/wsl2development/uze/uze-platform/node_modules/typescript/lib/typescript.js:124700:25)
    at Object.createProgram (/wsl2development/uze/uze-platform/node_modules/typescript/lib/typescript.js:579:28)
    at Object.createProgram (/wsl2development/uze/uze-platform/node_modules/typescript/lib/typescript.js:124691:41)
    at NestiaSdkApplication.<anonymous> (/wsl2development/uze/uze-platform/node_modules/@nestia/sdk/src/NestiaSdkApplication.ts:156:36)
    at Generator.next (<anonymous>)
    at fulfilled (/wsl2development/uze/uze-platform/node_modules/@nestia/sdk/lib/NestiaSdkApplication.js:5:58)
```

I've tried to update typescript to `5.5.4` with the same results. I rolled back to `5.4.2` and its working again. Im not sure if this is a `Nestia` or a `Typia` problem but i decided to post it here because it might only indirectly a Typia issue

**Comment by Devidian** [comment]
We always use latest, but i see my mistake, we should use `nestia setup` instead of `typia setup` in our pipeline. Nestia installs `5.4.2` and Typia `5.5.2`
