### ISSUE TITLE
@nestia/migrate does not support OpenAPI 3.1.0 'null' type 

### ISSUE THREAD

**Issue by fidgi** [samchon/nestia#983]
### Summary
@nestia/migrate does not support OpenAPI 3.1.0 'null' type

  - **SDK Version**: 5.5.0-dev.20240722
  - **Migrate should support full OpenAPI 3.1.0 specification**: 
  - **Migrate does not support 'null' type**: 

### Code occuring the bug

With the following OpenAPI specifcation file
```json
{
  "openapi": "3.1.0",
  "info": {
    "title": "Sample",
    "version": "1.0.0",
    "description": "sample",
    "license": {
      "name": "IST"
    }
  },
  "servers": [
    {
      "url": "https://nowhere.org/{version}",
      "description": "sample\n",
      "variables": {
        "version": {
          "default": "v1"
        }
      }
    }
  ],
  "paths": {
    "/user": {
      "get": {
        "summary": "Get user data",
        "description": "Get user data.<br>\n",
        "operationId": "getUserData",
        "parameters": [
          {
            "name": "id",
            "in": "query",
            "required": true,
            "description": "The numeric identifier of the user",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "description": "Get user data response.\n",
                  "type": "object",
                  "properties": {
                    "id": {
                      "description": "User id.\n",
                      "type": "string",
                      "example": "99899",
                      "pattern": "^\\d{1,9}$"
                    },
                    "name": {
                      "description": "User name.\n",
                      "type": [
                        "string",
                        "null"
                      ]
                    }
                  }
                }
              }
            }
          },
          "4XX": {
            "description": "error occurred - see status code and message for more information.",
            "content": {}
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "bearerAuth": {
        "description": "Use a JWT as an HTTP authentication bearer\n",
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    }
  }
}
```
Migrate fails 

```bash
npx @nestia/migrate
? Migration mode NestJS
? Swagger file location dist/specs/openapi-bundle.json
? Output directory path /tmp/test
? Mokup Simulator true
? Generate E2E tests true
[
  {
    path: '$input.paths["/user"].get.responses["200"].content["application/json"].schema.properties.name.type',
    expected: 'undefined',
    value: [ 'string', 'null' ]
  }
]
Error: Invalid swagger file (must follow the OpenAPI 3.0 spec).
    at /home/xxxx/.npm/_npx/42538cd42232552b/node_modules/@nestia/migrate/lib/internal/MigrateCommander.js:49:19
    at Generator.next (<anonymous>)
    at fulfilled (/home/xxxx/.npm/_npx/42538cd42232552b/node_modules/@nestia/migrate/lib/internal/MigrateCommander.js:5:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

```

**Comment by samchon** [comment]
Upgrade to `@nestia/mirate@0.17.0`, then the problem be solved.
