### ISSUE TITLE
nestia sdk (with clone option) fails with type error

### ISSUE THREAD

**Issue by sacru2red** [samchon/nestia#998]
## Bug Report
```
$ cd packages/api
$ npm run build

> @ORGANIZATION/PROJECT-api@0.1.0 build
> npm run build:sdk && npm run compile


> @ORGANIZATION/PROJECT-api@0.1.0 build:sdk
> rimraf ../../src/api/functional && cd ../.. && npx nestia sdk && cd packages/api

-----------------------------------------------------------
 Nestia SDK Generator
-----------------------------------------------------------
Analyzing reflections
  - controllers: #1
  - paths: #1
  - routes: #1
Analyzing soure codes
Generating SDK Library
TypeError: s.replace is not a function
    at escapeString (...node_modules\typescript\lib\typescript.js:20480:12)
    at escapeNonAsciiString (...node_modules\typescript\lib\typescript.js:20484:7)
    at getLiteralText (...node_modules\typescript\lib\typescript.js:17675:22)
    at getLiteralTextOfNode (...node_modules\typescript\lib\typescript.js:122402:12)
    at emitLiteral (...node_modules\typescript\lib\typescript.js:119769:18)
    at pipelineEmitWithHintWorker (...node_modules\typescript\lib\typescript.js:119613:18)
    at pipelineEmitWithHint (...node_modules\typescript\lib\typescript.js:119263:7)
    at pipelineEmitWithComments (...node_modules\typescript\lib\typescript.js:122908:5)
    at pipelineEmit (...node_modules\typescript\lib\typescript.js:119212:5)
    at emitExpression (...node_modules\typescript\lib\typescript.js:119196:5)
```

controller respone type is 
```
export type Message = {
  // no errors if toggle to comment under line
  type: 0 | 1;
  payload?: string;
};

export interface GetHelloResponseDto {
  messages?: Array<Message> | Readonly<Array<Message>>;
}
```

### Summary
Write a short summary of the bug in here.

  - **SDK Version**: 3.11.2
  - **Expected behavior**: working
  - **Actual behavior**: throw error

Write detailed description in here.

https://github.com/sacru2red/nestia-sample/tree/sdk-fails-type-error

**Comment by samchon** [comment]
Upgrade to v3.11.3, then be fixed.

Thanks for reporting.
